apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-deployment
  template:
    metadata:
      labels:
        app: product-deployment
    spec:
      containers:
      - name: product-deployment
        image: abhayjo/cc-backend-product:latest
        ports:
        - containerPort: 8001
        imagePullPolicy: Always

