apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: review-deployment
  template:
    metadata:
      labels:
        app: review-deployment
    spec:
      containers:
      - name: review-deployment
        image: abhayjo/cc-backend-review:latest
        ports:
        - containerPort: 8003
        imagePullPolicy: Always

